/**
 * Hypothesis Generator — Phase 2 Real Local LLM Inference
 *
 * ============================================================
 * WHAT THIS IS: this module builds a prompt from the FRF engine's
 * own deterministic output (an ObservedChange and its matched
 * RelationshipMatch[]) and sends it to a REAL, small, locally-running
 * language model (see model-loader.ts — Xenova/LaMini-Flan-T5-77M,
 * ~77M parameters, run via transformers.js/ONNX Runtime Web/WASM).
 * Inference happens on-device, in the browser, with no server, no
 * API call, and no external data transmission.
 *
 * WHAT THIS IS NOT: this is not a stock predictor, not investment
 * advice, and not a verified conclusion. The model is instructed to
 * summarize hypotheses and evidence that ALREADY EXIST in the FRF
 * knowledge base (built from FRF Master Specification §24.2 pairings
 * plus FinEve-authored explanatory text) — it is not asked to invent
 * new financial claims, and its output should be read as an
 * unverified, experimental restatement, not a fact.
 *
 * The `observation` field (what changed, by how much) remains a
 * deterministic, non-LLM computation — see buildObservation() below —
 * because that is exact arithmetic already computed by the FRF engine;
 * there is no reason to risk a small language model mis-stating a
 * number that is already known with certainty.
 * ============================================================
 *
 * Dependency direction: this module imports FROM frf-engine (as a
 * consumer of its types and output) and from model-loader.ts (the
 * only other file in ai/ that touches @huggingface/transformers).
 * frf-engine has zero dependency on this module or anything in ai/.
 */

import type { ObservedChange } from "../frf-engine/change-detection";
import type { RelationshipMatch } from "../frf-engine/relationship-lookup";
import { getGenerator, type ModelStatus } from "./model-loader";

/**
 * A single structured hypothesis, one per matched FRF relationship.
 */
export interface AnalystHypothesis {
  relationship_id: string;
  /** What was observed: the parameter, its direction, and magnitude. Deterministic, not LLM-generated. */
  observation: string;
  /** A short natural-language synthesis generated by the local model, grounded in possible_explanations. */
  possible_hypothesis: string;
  /** Where to check: drawn directly from evidence_to_check (not LLM-generated — these are exact disclosure locations). */
  evidence_to_verify: string;
}

const percentFormatter = new Intl.NumberFormat("en-IN", {
  maximumFractionDigits: 2,
  signDisplay: "always",
});

/**
 * Builds the deterministic observation sentence for a change. Pure
 * function, no model call — exact arithmetic the FRF engine already
 * computed should never be re-derived by a language model.
 */
export function buildObservation(change: ObservedChange, match: RelationshipMatch): string {
  const directionWord = change.direction === "increase" ? "increased" : "decreased";
  const arrow = change.direction === "increase" ? "↑" : "↓";
  return (
    `${match.observed_parameter.name} ${directionWord} ${arrow} by ` +
    `${percentFormatter.format(change.percent_change)}% (from ${change.from_value} to ${change.to_value}, ` +
    `${change.from_period} → ${change.to_period}).`
  );
}

/**
 * Builds the exact evidence_to_verify string for a match. Pure
 * function, no model call — these are fixed disclosure locations from
 * the knowledge base, not something a language model should paraphrase
 * or risk altering.
 */
export function buildEvidenceToVerify(match: RelationshipMatch): string {
  return match.relationship.evidence_to_check.length > 0
    ? match.relationship.evidence_to_check.join("; ")
    : "No evidence locations recorded for this relationship.";
}

/**
 * Builds the prompt sent to the local model. Pure function, fully
 * testable without invoking the model. The prompt explicitly instructs
 * the model to work only from the given explanations, rather than
 * inventing new financial claims.
 */
export function buildPrompt(change: ObservedChange, match: RelationshipMatch): string {
  const observation = buildObservation(change, match);
  const explanations =
    match.relationship.possible_explanations.length > 0
      ? match.relationship.possible_explanations.join("; ")
      : "no recorded explanations";

  return (
    `You are summarizing a financial analysis finding in ONE short sentence. ` +
    `Observation: ${observation} ` +
    `Related parameter to investigate: ${match.related_parameter.name}. ` +
    `Recorded possible explanations for this pattern: ${explanations}. ` +
    `Write a brief, plain-language hypothesis based ONLY on the explanations given above. ` +
    `Do not invent new numbers or new explanations not listed.`
  );
}

/**
 * Calls the local model to generate the possible_hypothesis text for
 * one match. This is the only function in this module that actually
 * performs inference; everything else here is pure and synchronous.
 *
 * onStatusChange is forwarded to the model loader so callers can show
 * a loading state on first use (model download/initialization).
 */
async function generatePossibleHypothesis(
  change: ObservedChange,
  match: RelationshipMatch,
  onStatusChange?: (status: ModelStatus) => void
): Promise<string> {
  const generator = await getGenerator(onStatusChange);
  const prompt = buildPrompt(change, match);

  const output = await generator(prompt, {
    max_new_tokens: 80,
    temperature: 0.7,
    repetition_penalty: 1.3,
  });

  const text = output[0]?.generated_text?.trim();
  return text && text.length > 0
    ? text
    : match.relationship.possible_explanations.join("; ") || "No hypothesis generated.";
}

/**
 * Builds one AnalystHypothesis per matched relationship for a single
 * observed change, using real local model inference for the
 * possible_hypothesis field. observation and evidence_to_verify remain
 * deterministic (see buildObservation/buildEvidenceToVerify above).
 *
 * If matches is empty, returns an empty array immediately without
 * touching the model — this function never fabricates a hypothesis
 * when the deterministic engine found no relationship.
 *
 * If model inference fails for a given match (e.g. the model failed to
 * load), that hypothesis's possible_hypothesis falls back to the raw
 * possible_explanations text rather than throwing and losing the whole
 * result — the caller still gets a usable (if less polished) result.
 */
export async function generateHypotheses(
  change: ObservedChange,
  matches: RelationshipMatch[],
  onStatusChange?: (status: ModelStatus) => void
): Promise<AnalystHypothesis[]> {
  if (matches.length === 0) {
    return [];
  }

  const results: AnalystHypothesis[] = [];
  for (const match of matches) {
    let possible_hypothesis: string;
    try {
      possible_hypothesis = await generatePossibleHypothesis(change, match, onStatusChange);
    } catch {
      // Fall back to the raw recorded explanations rather than losing
      // this hypothesis entirely if the model call fails.
      possible_hypothesis =
        match.relationship.possible_explanations.join("; ") || "No hypothesis generated.";
    }

    results.push({
      relationship_id: match.relationship.relationship_id,
      observation: buildObservation(change, match),
      possible_hypothesis,
      evidence_to_verify: buildEvidenceToVerify(match),
    });
  }

  return results;
}
